
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:  
  - name: install Docker
    yum: 
      name: docker
      update_cache: yes
      state: present
  - name: add ubuntu to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes
  - name: install python-pip
    yum:
      name: python-pip
      state: present
  - name: install docker-py
    pip:
      name: docker-py
  - name: install Docker Compose
    pip:
      name: docker-compose
      version: 1.9.0
  - name: copy docker-compose.yml
    copy:
      src: ./docker-compose.yml
      dest: ./docker-compose.yml
  - name: run docker-compose
    docker_service:
      project_src: .
      state: present
      restarted: yes
