pipeline {
     agent any
     stages {
        stage("Checkout") {
            steps {
                git url: 'https://github.com/nagabhushanamn/calculator.git'
            }
          }
        stage("Compile") {
		    steps {
                script{
                    def project = 'web-calculator'
                    dir(project){
                    		sh "./gradlew compileJava"    
                    }
                }
		    }
		}
		stage("Unit test") {
			steps{
			    script{
                    def project = 'web-calculator'
                    dir(project){
                    		sh "./gradlew test"    
                    }
                }
			}
		}
		stage("Code coverage") {
		    steps {
		       script{
                    def project = 'web-calculator'
                    dir(project){
				        sh "./gradlew jacocoTestReport"
                        publishHTML (target: [
                            reportDir: 'build/reports/jacoco/test/html',
                            reportFiles: 'index.html',
                            reportName: "JaCoCo Report"
                        ])
				        sh "./gradlew jacocoTestCoverageVerification"
				    }
		         }
		     }
		}
        stage("Static code analysis") {
            steps {
                script{
                    def project = 'web-calculator'
                    dir(project){
                         sh "./gradlew checkstyleMain"
                         publishHTML (target: [
                            reportDir: 'build/reports/checkstyle/',
                            reportFiles: 'main.html',
                            reportName: "Checkstyle Report"
                        ])
                    }
                 }
            }     
        }
        stage("Package") {
            steps {
                script{
                    def project = 'web-calculator'
                    dir(project){
                        sh "./gradlew build"
                    }
                }
            }
        }

    
        stage("Docker Build") {
            steps {
                script{
                    def project = 'web-calculator'
                    dir(project){
                        sh "docker build -t localhost:5000/calculator ."
                    }
                }
            }
        }
        stage("Docker Push") {
            steps {
                sh "docker push localhost:5000/calculator"
            }
         }
         
        // stage("Deploy to staging") {
        //      steps {
        //          sh "docker run -d --rm -p 8765:8080 --name calculator localhost:5000/calculator"
        //      }
        //  }

        stage("Deploy to staging") {
            steps {
                script{
                    def project = 'web-calculator'
                    dir(project){
                        sh "/usr/local/bin/docker-compose up -d"
                    }
                }
            }
        }
        
        // a. Method 1 – Jenkins-first acceptance testing

        stage("Acceptance test") {
           steps { 
            script{
                    def project = 'web-calculator'
                    dir(project){
                        sleep 10
                        sh 'chmod +x acceptance_test.sh'
                        sh "./acceptance_test.sh"
                    }
                }
           }
        }

        // Method 2 – Docker-first acceptance testing

        // stage("Acceptance test") {
        //     steps {
        //         script{
        //             def project = 'web-calculator'
        //             dir(project){
        //                 sh "docker-compose -f docker-compose.yml -f acceptance/docker-compose-acceptance.yml build test"
        //                 sh "docker-compose -f docker-compose.yml -f acceptance/docker-compose-acceptance.yml -p acceptance up -d"
        //                 sh 'test $(docker wait acceptance_test_1) -eq 0'
        //             }
        //         }
        //     }
        // }

     }  
     post {
        always {
            
            //mail to: 'team@company.com',
            //subject: "Completed Pipeline: ${currentBuild.fullDisplayName}",
            //body: "Your build completed, please check: ${env.BUILD_URL}"
            
            //sh "docker stop calculator"
             script{
                    def project = 'web-calculator'
                    dir(project){
            			sh "/usr/local/bin/docker-compose down"
                        // sh "docker-compose -f docker-compose.yml -f acceptance/docker-compose-acceptance.yml -p acceptance down"
           			}
            }
        }
    }
}